### PR TITLE
Implement join group logic

### PR DESCRIPTION
**Pull request by huyouare**

### CODE REVIEW

**Comment by JustinLovesCompsci** [comment]
According to https://parse.com/questions/setting-properties-to-nil-on-a-subclassed-pfobject
PFObject can never be nil, but it can be NSNull(), which is the Parse standard. Not sure if you should compare the fields with nil (maybe NSNull() instead)? 

Also, in GroupsViewController, it only displays the groups the current user is already in. So not sure if you still need to check if the user is contained in the users array in didSelectGroup() logic. This way, it is easier for the user to manage. He/she only sees the group he already joined in the main group view. If he/she wants to join a new one, he/she would browse through the course and join there instead.

**Comment by huyouare** [comment]
The answer in that post is down-voted plenty. Could you go into my commit and comment on the line that you're concerned about? The logic for dateTime being nil works; strings are checked by character (glyph) count. 

For the didSelectGroup logic, I'm checking to see if the user already belongs to that group, so we don't add another copy of that PFUser to the group. See 68e5b2d

**Comment by JustinLovesCompsci** [comment]
Okay, then I guess nil works fine. 

What I am thinking is that the current PFUser has to be in the group already. Otherwise, the user will not be able to see the group displayed in the GroupsView. So the extra check and add user to group may not be necessary in the didSelectGroup(). Right?

**Comment by huyouare** [comment]
Why would the user be in the group? didSelectGroup is the delegate method for joining a group from GroupSelectVC. I'll rename it to joinGroup.

Also @JustinLovesCompsci I didn't want #20 merged before #19. I'm getting merge conflicts.

**Comment by JustinLovesCompsci** [comment]
On line 82 of SwiftParseChat/GroupsViewController.swift, see #16 . I have added one line which will only load groups that the current PFUser is already in at the GroupView. So the user should only see the groups he/she already joined before in the GroupView.

**Comment by JustinLovesCompsci** [comment]
Sorry, thought #20 would be independent of #19 . But I see #20 just added a couple lines so the merge conflicts won't be hard to deal with.

**Comment by huyouare** [comment]
Yes - that logic makes sense (though it uses a search through the array rather than bi-directional pointers, that's fine).
didSelectGroup is for adding yourself to a new group.

**Comment by JustinLovesCompsci** [comment]
Oh I see what you mean sry. you are right

**Comment by JustinLovesCompsci** [comment]
once you solved the merge conflict, you should be good to go

**Comment by huyouare** [comment]
@JustinLovesCompsci Cool. Just so we're consistent, do you want to ditch the bi-directional pointers? Meaning, we query groups for groups that the user belongs to, rather than querying user for groups that the user has?

**Comment by JustinLovesCompsci** [comment]
I was following this guide (array for many-to-many relations) from Parse: https://parse.com/docs/relations_guide

Did not see the bi-directional pointers there. Do you mean we have an extra column in users table that contains an array of group pointers? That would be a bit redundant

**Pull request merged**
